broadcast/accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/', views.ProfileView.as_view(), name='profile'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='broadcast/auths/password_change_done.html'),
         name='password_change_done'),

    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='broadcast/auths/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done')
        ),
        name='password_change'
    ),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='broadcast/auths/password_reset_done.html'),
         name='password_reset_done'),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='broadcast/auths/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='broadcast/auths/password_reset_form.html',
             email_template_name='broadcast/auths/password_reset_email.html',
             success_url=reverse_lazy("accounts:password_reset_done")
         ),
         name='password_reset'
         ),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='broadcast/auths/password_reset_complete.html'),
         name='password_reset_complete'),
]

broadcast/broadcast/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

broadcast/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexPage.as_view(), name='index_page'),
    path('playlist/', views.PlaylistView.as_view(), name='playlist'),
    path('add-to-favorite/', views.AddToFavorite.as_view(), name='add_to_favorite'),
    path('broadcast/', views.BroadcastView.as_view(), name='broadcast'),

]

broadcast/broadcast/templates/broadcast/auths/password_change.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>
{% if messages %} {% for message in messages %}
<span>{{message}}</span>
{% endfor %} {% endif %}
<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Change Password</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <form method="post">{% csrf_token %}
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="password" name="old_password" placeholder="Enter old password" required />
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="password" name="new_password1" placeholder="Enter new password" required />
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="password" name="new_password2" placeholder="Retype new password" required />
          </div>
          <input class="button" type="submit" value="Change Password" />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

broadcast/broadcast/templates/broadcast/auths/password_change_done.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>
{% if messages %} {% for message in messages %}
<span>{{message}}</span>
{% endfor %} {% endif %}
<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Password Updated Successfully</h2>
    </div>
  </div>
</div>

{% endblock body %}

broadcast/broadcast/templates/broadcast/auths/password_reset_complete.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>
{% if messages %} {% for message in messages %}
<span>{{message}}</span>
{% endfor %} {% endif %}
<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Password Reset</h2>
    </div>
    <div class="row clearfix">
      <div class="">
		  <p>Your password has been reset. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now.</p>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

broadcast/broadcast/templates/broadcast/auths/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>
{% if messages %} {% for message in messages %}
<span>{{message}}</span>
{% endfor %} {% endif %}
<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Password Reset</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <form method="post">{% csrf_token %}
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="password" name="new_password1" placeholder="Enter new password" required />
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="password" name="new_password2" placeholder="Re-enter new passwor" required />
          </div>
          <p><a href="{% url 'core:index_page' %}">Go To Home Page</a></p>
          <input class="button" type="submit" value="Submit" />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

broadcast/broadcast/templates/broadcast/auths/password_reset_done.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>
{% if messages %} {% for message in messages %}
<span>{{message}}</span>
{% endfor %} {% endif %}
<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Password Reset</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <p>
			We've emailed you instructions for setting your password, if an account exists with the email you entered.
			You should receive them shortly.
		</p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'core:index_page' %}">Return to home page</a></p>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

broadcast/broadcast/templates/broadcast/auths/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Broadcast Platform Team
{% endautoescape %}

broadcast/broadcast/templates/broadcast/auths/password_reset_form.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>
{% if messages %} {% for message in messages %}
<span>{{message}}</span>
{% endfor %} {% endif %}
<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Password Reset</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <form method="post">{% csrf_token %}
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="email" name="email" placeholder="Enter your email address" required />
          </div>
          <input class="button" type="submit" value="Send reset email" />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock body %}