broadcast/accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/', views.ProfileView.as_view(), name='profile'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='broadcast/auths/password_change_done.html'),
         name='password_change_done'),

    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='broadcast/auths/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done')
        ),
        name='password_change'
    ),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='broadcast/auths/password_reset_done.html'),
         name='password_reset_done'),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='broadcast/auths/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='broadcast/auths/password_reset_form.html',
             email_template_name='broadcast/auths/password_reset_email.html',
             success_url=reverse_lazy("accounts:password_reset_done")
         ),
         name='password_reset'
         ),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='broadcast/auths/password_reset_complete.html'),
         name='password_reset_complete'),
]

broadcast/broadcast/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

broadcast/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexPage.as_view(), name='index_page'),
    path('playlist/', views.PlaylistView.as_view(), name='playlist'),
    path('add-to-favorite/', views.AddToFavorite.as_view(), name='add_to_favorite'),
    path('broadcast/', views.BroadcastView.as_view(), name='broadcast'),

]

broadcast/broadcast/templates/broadcast/broadcast.html
{% extends "base.html" %}
{% load static %}
{% load embed_video_tags %}

{% block morecss %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
  body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #04AA6D;
  color: white;
}

.topnav .icon {
  display: none;
}

@media screen and (max-width: 600px) {
  .topnav a:not(:first-child) {display: none;}
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
}
</style>
{% endblock morecss %}

{% block body %}

<body>

<div class="topnav" id="myTopnav">
  <a href="/" class="active">Home</a>
  <a href="{% url 'core:playlist' %}">Playlist</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>
  <div>
    <h1>All Broadcasts</h1>
  </div>
  <div class="main-container">
    {% if obj %}
      {% for x in obj %}
        {% video x.url 'small' %}
      {% endfor %}
    {% else %}
      <h1>No Broadcast Yet</h1>
    {% endif %}
  </div>
</body>

{% endblock body %}
{% block extrajs %}
<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>
{% endblock extrajs %}

broadcast/broadcast/templates/broadcast/home.html
{% extends "base.html" %}
{% load static %}
{% load embed_video_tags %}

{% block morecss %}
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'fontawesome-free-5.15.3-web/css/all.min.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>
<div class="main-container">
    {% if messages %} {% for message in messages %}
<span>{{message}}</span>
{% endfor %} {% endif %}
    <div class="background-text">
    </div>
    <header class="header">
        <a href="/" id="logo">Broadcast Platform</a>
        <nav class="navbar">
            <a href="/">home</a>
            {% if user.is_authenticated %}
            <a href="{% url 'core:broadcast' %}">Broadcasts</a>
            <a href="{% url 'core:playlist' %}">Playlist</a>
            <a href="{% url 'accounts:profile' %}">Profile</a>
            <a href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'accounts:login' %}">sign in</a>
            <a href="{% url 'accounts:sign-up' %}">sign up</a>
            {% endif %}
        </nav>
        <a href="#" id="menu-bars" class="fas fa-bars"></a>
    </header>
    <div class="taxi-image">
        <img src="{% static 'images/D.png' %}" alt="">
    </div>
</div>

<!-- home section -->
<div class="home-container">
    <div class="home-content">
        <div class="inner-content">
            <h3>best in city</h3>
            <h2>{{sports.title}}</h2>
            <p>The 2022 FIFA World Cup is scheduled to be the 22nd running of the FIFA World Cup competition, the quadrennial international men's football championship contested by the national teams of the member associations of FIFA. It is scheduled to take place in Qatar from 21 November to 18 December 2022.</p>
            <a href="/" class="booknow">stay updated</a>
        </div>
        <div class="inner-content">
                {% video sports.url 'small' %}

        </div>
    </div>
</div>
<!-- home section ended -->

<!-- our tariff -->

<div class="main-tariff">
    <a href="{% url 'core:broadcast' %}"><h1>our <span>broadcasts</span></h1></a>
    <div class="inner-tarrif">
        <div class="tarrif-container" style="border: 1px solid gray">
            <div class="inner-box">
                <h2>{{sports.title}}</h2>
                {% video sports.url 'small' %}
                <h3 style="padding: 2rem">{{sports.genre}}</h3>
                {% if sports.is_in_playlist %}
                <button class="add-to-playlist" disabled>Already In Playlist</button>
                {% else %}
                <button class="add-to-playlist" onclick="addToFavorite('{{sports.id}}')">Add To Playlist</button>
                {% endif %}
            </div>
        </div>

        <div class="tarrif-container" style="border: 1px solid gray">
            <div class="inner-box">
                <h2>{{news.title}}</h2>
                {% video news.url 'small' %}
                <h3 style="padding-top: 2rem">{{news.genre}}</h3>
                {% if news.is_in_playlist %}
                <button class="add-to-playlist" disabled>Already In Playlist</button>
                {% else %}
                <button class="add-to-playlist" onclick="addToFavorite('{{news.id}}')">Add To Playlist</button>
                {% endif %}
            </div>
        </div>

    </div>

</div>

<div class="testimonials">
    <a href="{% url 'core:playlist' %}"><h1 class="heading-test">Playlist</h1></a>
    <div class="main-testimonials">
        <div class="inner-test">
            {% if playlist %}
                {% for x in playlist %}
                    {% video x.broadcast.url 'small' %}
                {% endfor %}
            {% else %}
                <h1>No Item In Your Playlist</h1>
            {% endif %}
        </div>
    </div>
</div>

<script src="{% static 'js/script.js' %}" ></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}" ></script>


</body>

{% endblock body %}

{% block extrajs %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
    function addToFavorite(id) {
        console.log("Called function")
        $.ajax({
            type:'POST',
            url:"{% url 'core:add_to_favorite' %}",
            data: {
                id:id,
                csrfmiddlewaretoken: '{{ csrf_token }}'
                // csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]')
            },

            success:response => {
                alert("Successfully added to your playlist")
            }
        })
    }

</script>
{% endblock extrajs %}

broadcast/broadcast/templates/broadcast/login.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>

<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Login</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <form method="post">{% csrf_token %}
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="text" name="username" placeholder="Username" required />
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="password" name="password" placeholder="Email" required />
          </div>
          {% if messages %} {% for message in messages %}
          <span style="color: red"><strong>{{message}}</strong></span>
          {% endfor %} {% endif %}
          <p><a href="{% url 'accounts:password_reset' %}">Forgot Password?</a></p>
          <p>Don't have an account yet? <a href="{% url 'accounts:sign-up' %}">Sign Up</a></p>
          <input class="button" type="submit" value="Login" />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

broadcast/broadcast/templates/broadcast/playlist.html
{% extends "base.html" %}
{% load static %}
{% load embed_video_tags %}

{% block morecss %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
  body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #04AA6D;
  color: white;
}

.topnav .icon {
  display: none;
}

@media screen and (max-width: 600px) {
  .topnav a:not(:first-child) {display: none;}
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
}
</style>
{% endblock morecss %}

{% block body %}

<body>

<div class="topnav" id="myTopnav">
  <a href="/" class="active">Home</a>
  <a href="{% url 'core:broadcast' %}">Broadcasts</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>
  <div>
    <h1>All Broadcasts</h1>
  </div>
  <div class="main-container">
    {% if obj %}
      {% for x in obj %}
        {% video x.broadcast.url 'small' %}
      {% endfor %}
    {% else %}
      <h1>You don't have any playlist yet</h1>
    {% endif %}
  </div>
</body>

{% endblock body %}

{% block extrajs %}
<script>
  console.log('{{obj}}')
</script>
{% endblock extrajs %}

broadcast/broadcast/templates/broadcast/profile.html
{% extends "base.html" %}
{% load static %}
{% load embed_video_tags %}

{% block morecss %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="{% static 'css/profilecss.css' %}" rel="stylesheet">
<style>
  body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #04AA6D;
  color: white;
}

.topnav .icon {
  display: none;
}

@media screen and (max-width: 600px) {
  .topnav a:not(:first-child) {display: none;}
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
}
</style>
{% endblock morecss %}

{% block body %}

<body>

<div class="topnav" id="myTopnav">
  <a href="/" class="active">Home</a>
  <a href="{% url 'core:broadcast' %}">Broadcasts</a>
    <a href="{% url 'core:playlist' %}">Playlist</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>

<div class="container">
<!--  <div class="avatar-flip">-->
<!--    <img src="http://media.idownloadblog.com/wp-content/uploads/2012/04/Phil-Schiller-headshot-e1362692403868.jpg" height="150" width="150">-->
    <img src="{% static 'images/avarta.png' %}" height="150" width="150">
<!--  </div>-->
  <h2>Username</h2>
  <h4>{{user.username}}</h4>
  <h2>Favorite Broadcasts</h2>
  <h4>{{playlist.count}}</h4>
  <h2>Date Joined</h2>
  <h4>{{user.created_at.date}}</h4>
</div>

{% endblock body %}

broadcast/broadcast/templates/broadcast/register.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
<link href="{% static 'css/registercss.css' %}" rel="stylesheet">
{% endblock morecss %}

{% block body %}

<body>

<div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Broadcast Platform Registration Form</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <form method="post">{% csrf_token %}
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="text" name="username" placeholder="Username" required />
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
            <input type="email" name="email" placeholder="Email" required />
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-lock"></i></span>
            <input type="password" name="password1" placeholder="Password" required />
          </div>
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-lock"></i></span>
            <input type="password" name="password2" placeholder="Re-type Password" required />
          </div>
          <div class="row clearfix">
            <div class="col_half">
              <div class="input_field"> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                <input type="text" name="first_name" placeholder="First Name" />
              </div>
            </div>
            <div class="col_half">
              <div class="input_field"> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                <input type="text" name="last_name" placeholder="Last Name" required />
              </div>
            </div>
          </div>
          <p>Already have an account? <a href="{% url 'accounts:login' %}">Sign In</a></p>
<!--          <div class="input_field radio_option">-->
<!--            <input type="radio" name="radiogroup1" id="rd1">-->
<!--            <label for="rd1">Male</label>-->
<!--            <input type="radio" name="radiogroup1" id="rd2">-->
<!--            <label for="rd2">Female</label>-->
<!--          </div>-->

<!--            <div class="input_field checkbox_option">-->
<!--            	<input type="checkbox" id="cb1">-->
<!--    			<label for="cb1">I agree with terms and conditions</label>-->
<!--            </div>-->
<!--            <div class="input_field checkbox_option">-->
<!--            	<input type="checkbox" id="cb2">-->
<!--    			<label for="cb2">I want to receive the newsletter</label>-->
<!--            </div>-->
          <input class="button" type="submit" value="Register" />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock body %}